import Head from "next/head"
import { useState } from "react"

export default function Home() {
  const [content, setContent] = useState([])

  const handleChange = (event: any) => {
    setContent(event.target.value)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white flex flex-col">
        <h1 className="text-3xl font-bold self-center py-10">
          文字数チェッカー
        </h1>
        <textarea
          value={content}
          onChange={handleChange}
          rows="10"
          cols="60"
          className="bg-slate-200 text-slate-800 rounded outline text-lg p-4 self-center m-10"
        />
        <div className="self-center m-10">
          <p className="text-3xl font-bold ">{content.length}</p>
        </div>
      </main>
    </>
  )
}
