import Head from "next/head"
import { useState } from "react"

export default function Home() {
  const [content, setContent] = useState<string>("")

  const handleChange = (event: any) => {
    setContent(event.target.value)
  }

  const checkLetterLength = (content: string, letter: string): number => {
    const letterLength = content.split("").filter((x) => x === letter).length
    return letterLength
  }

  const contentStr = content.toString()

  const paste = async () => {
    await global.navigator.clipboard
      .readText()
      .then((clipText) => setContent(clipText))
  }

  return (
    <>
      <Head>
        <title>文字数チェッカー</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-gradient-to-r dark:from-slate-900 dark:to-slate-700 flex flex-col box-border p-10 dark:text-slate-200">
        <h1 className="text-3xl font-bold self-center py-10 ">
          文字数チェッカー
        </h1>
        <div className="w-full max-w-2xl self-center flex flex-col">
          <button
            onClick={paste}
            className="px-4 py-2 outline w-20 rounded self-end outline-2 bg-slate-200 dark:text-slate-900"
          >
            paste
          </button>
          <textarea
            value={content}
            onChange={handleChange}
            className="bg-slate-200 text-slate-800 rounded outline text-lg p-4 my-8 h-96 max-h-screen"
          />
        </div>
        <div className="self-center m-10">
          <p className="text-xl">
            計
            <strong className="text-3xl font-bold px-1">
              {content.length - checkLetterLength(contentStr, "/n")}
            </strong>
            文字
          </p>
        </div>
        <div className="outline rounded p-2 m-4">
          <p>
            空白文字(合計) :
            {checkLetterLength(contentStr, " ") +
              checkLetterLength(contentStr, "　")}
          </p>
          <p>空白文字(半角) : {checkLetterLength(contentStr, " ")}</p>
          <p>空白文字(全角) : {checkLetterLength(contentStr, "　")}</p>
          <p>句点 : {checkLetterLength(contentStr, "、")}</p>
          <p>読点 : {checkLetterLength(contentStr, "。")}</p>
        </div>
      </main>
    </>
  )
}
